var letters={
    "letters":[
        {
            "symbol":"A",
            "draw":[
                "▓▓▓▓▓▓▓▓▓▓▓",
                "▓AAAAAAAAA▓",
                "▓AAA▓▓▓AAA▓",
                "▓AAA▓▓▓AAA▓",
                "▓AAAAAAAAA▓",
                "▓AAA▓▓▓AAA▓",
                "▓AAA▓▓▓AAA▓",
                "▓AAA▓▓▓AAA▓",
                "▓▓▓▓▓▓▓▓▓▓▓"
            ]
        },
        {
            "symbol":"B",
            "draw":[
                "▓▓▓▓▓▓▓▓▓▓▓",
                "▓BBBBBBBB▓▓",
                "▓BBB▓▓▓BBB▓",
                "▓BBB▓▓▓BBB▓",
                "▓BBBBBBBB▓▓",
                "▓BBB▓▓▓BBB▓",
                "▓BBB▓▓▓BBB▓",
                "▓BBBBBBBB▓▓",
                "▓▓▓▓▓▓▓▓▓▓▓"
            ]
        },
        {
            "symbol":"C",
            "draw":[
                "▓▓▓▓▓▓▓▓▓▓▓",
                "▓CCCCCCCCC▓",
                "▓CCCCCCCC▓▓",
                "▓CCC▓▓▓▓▓▓▓",
                "▓CCC▓▓▓▓▓▓▓",
                "▓CCC▓▓▓▓▓▓▓",
                "▓CCCCCCCC▓▓",
                "▓CCCCCCCCC▓",
                "▓▓▓▓▓▓▓▓▓▓▓"
            ]
        },
        {
            "symbol":"D",
            "draw":[
                "▓▓▓▓▓▓▓▓▓▓▓",
                "▓DDDDDDD▓▓▓",
                "▓DDD▓▓▓DDD▓",
                "▓DDD▓▓▓DDD▓",
                "▓DDD▓▓▓DDD▓",
                "▓DDD▓▓▓DDD▓",
                "▓DDD▓▓▓DDD▓",
                "▓DDDDDDD▓▓▓",
                "▓▓▓▓▓▓▓▓▓▓▓"
            ]
        },
        {
            "symbol":"E",
            "draw":[
                "▓▓▓▓▓▓▓▓▓▓▓",
                "▓EEEEEEEEE▓",
                "▓EEE▓▓▓▓▓▓▓",
                "▓EEE▓▓▓▓▓▓▓",
                "▓EEEEEEEEE▓",
                "▓EEE▓▓▓▓▓▓▓",
                "▓EEE▓▓▓▓▓▓▓",
                "▓EEEEEEEEE▓",
                "▓▓▓▓▓▓▓▓▓▓▓"
            ]
        },
        {
            "symbol":"F",
            "draw":[
                "▓▓▓▓▓▓▓▓▓▓▓",
                "▓FFFFFFFFF▓",
                "▓FFFFFFFFF▓",
                "▓FFF▓▓▓▓▓▓▓",
                "▓FFFFFFFFF▓",
                "▓FFF▓▓▓▓▓▓▓",
                "▓FFF▓▓▓▓▓▓▓",
                "▓FFF▓▓▓▓▓▓▓",
                "▓▓▓▓▓▓▓▓▓▓▓"
            ]
        },
        {
            "symbol":"G",
            "draw":[
                "▓▓▓▓▓▓▓▓▓▓▓",
                "▓GGGGGGGGG▓",
                "▓GGG▓▓▓▓GG▓",
                "▓GGG▓▓▓▓▓▓▓",
                "▓GGG▓GGGGG▓",
                "▓GGG▓▓▓▓GG▓",
                "▓GGG▓▓▓▓GG▓",
                "▓GGGGGGGGG▓",
                "▓▓▓▓▓▓▓▓▓▓▓"
            ]
        },
        {
            "symbol":"H",
            "draw":[
                "▓▓▓▓▓▓▓▓▓▓▓",
                "▓HHH▓▓▓HHH▓",
                "▓HHH▓▓▓HHH▓",
                "▓HHH▓▓▓HHH▓",
                "▓HHHHHHHHH▓",
                "▓HHH▓▓▓HHH▓",
                "▓HHH▓▓▓HHH▓",
                "▓HHH▓▓▓HHH▓",
                "▓▓▓▓▓▓▓▓▓▓▓"
            ]
        },
        {
            "symbol":"I",
            "draw":[
                "▓▓▓▓▓▓▓▓▓▓▓",
                "▓IIIIQIIII▓",
                "▓▓▓▓III▓▓▓▓",
                "▓▓▓▓III▓▓▓▓",
                "▓▓▓▓III▓▓▓▓",
                "▓▓▓▓III▓▓▓▓",
                "▓▓▓▓III▓▓▓▓",
                "▓IIIIIIIII▓",
                "▓▓▓▓▓▓▓▓▓▓▓"
            ]
        },
        {
            "symbol":"J",
            "draw":[
                "▓▓▓▓▓▓▓▓▓▓▓",
                "▓JJJJJJJJJ▓",
                "▓▓▓▓▓JJJ▓▓▓",
                "▓▓▓▓▓JJJ▓▓▓",
                "▓▓▓▓▓JJJ▓▓▓",
                "▓▓▓▓▓JJJ▓▓▓",
                "▓JJ▓▓JJJ▓▓▓",
                "▓JJJJJJJ▓▓▓",
                "▓▓▓▓▓▓▓▓▓▓▓"
            ]
        },
        {
            "symbol":"K",
            "draw":[
                "▓▓▓▓▓▓▓▓▓▓▓",
                "▓KKK▓▓▓KKK▓",
                "▓KKK▓▓KK▓▓",
                "▓KKK▓KK▓▓▓▓",
                "▓KKKK▓▓▓▓▓▓",
                "▓KKK▓KK▓▓▓▓",
                "▓KKK▓▓KK▓▓▓",
                "▓KKK▓▓▓KKK▓",
                "▓▓▓▓▓▓▓▓▓▓▓"
            ]
        },
        {
            "symbol":"L",
            "draw":[
                "▓▓▓▓▓▓▓▓▓▓▓",
                "▓LLL▓▓▓▓▓▓▓",
                "▓LLL▓▓▓▓▓▓▓",
                "▓LLL▓▓▓▓▓▓▓",
                "▓LLL▓▓▓▓▓▓▓",
                "▓LLL▓▓▓▓▓▓▓",
                "▓LLLLLLLLL▓",
                "▓LLLLLLLLL▓",
                "▓▓▓▓▓▓▓▓▓▓▓"
            ]
        },
        {
            "symbol":"M",
            "draw":[
                "▓▓▓▓▓▓▓▓▓▓▓",
                "▓MMM▓▓▓MMM▓",
                "▓MMMM▓MMMM▓",
                "▓MM▓MMM▓MM▓",
                "▓MM▓▓M▓▓MM▓",
                "▓MM▓▓▓▓▓MM▓",
                "▓MM▓▓▓▓▓MM▓",
                "▓MM▓▓▓▓▓MM▓",
                "▓▓▓▓▓▓▓▓▓▓▓"
            ]
        },
        {
            "symbol":"N",
            "draw":[
                "▓▓▓▓▓▓▓▓▓▓▓",
                "▓NNNN▓▓▓NN▓",
                "▓NNNN▓▓▓NN▓",
                "▓NN▓NN▓▓NN▓",
                "▓NN▓▓NN▓NN▓",
                "▓NN▓▓NN▓NN▓",
                "▓NN▓▓▓NNNN▓",
                "▓NN▓▓▓NNNN▓",
                "▓▓▓▓▓▓▓▓▓▓▓"
            ]
        },
        {
            "symbol":"Ñ",
            "draw":[
                "▓▓ÑÑÑÑÑÑÑ▓▓",
                "▓▓▓▓▓▓▓▓▓▓▓",
                "▓ÑÑÑÑ▓▓▓ÑÑ▓",
                "▓ÑÑÑÑ▓▓▓ÑÑ▓",
                "▓ÑÑ▓ÑÑ▓▓ÑÑ▓",
                "▓ÑÑ▓▓ÑÑ▓ÑÑ▓",
                "▓ÑÑ▓▓ÑÑ▓ÑÑ▓",
                "▓ÑÑ▓▓▓ÑÑÑÑ▓",
                "▓▓▓▓▓▓▓▓▓▓▓"
            ]
        },
        {
            "symbol":"O",
            "draw":[
                "▓▓▓▓▓▓▓▓▓▓▓",
                "▓▓OOOOOOO▓▓",
                "▓OOO▓▓▓OOO▓",
                "▓OOO▓▓▓OOO▓",
                "▓OOO▓▓▓OOO▓",
                "▓OOO▓▓▓OOO▓",
                "▓OOO▓▓▓OOO▓",
                "▓▓OOOOOOO▓▓",
                "▓▓▓▓▓▓▓▓▓▓▓"
            ]
        },
        {
            "symbol":"P",
            "draw":[
                "▓▓▓▓▓▓▓▓▓▓▓",
                "▓PPPPPPPP▓▓",
                "▓PPP▓▓▓PPP▓",
                "▓PPP▓▓▓PPP▓",
                "▓PPPPPPPP▓▓",
                "▓PPP▓▓▓▓▓▓▓",
                "▓PPP▓▓▓▓▓▓▓",
                "▓PPP▓▓▓▓▓▓▓",
                "▓▓▓▓▓▓▓▓▓▓▓"
            ]
        },
        {
            "symbol":"Q",
            "draw":[
                "▓▓▓▓▓▓▓▓▓▓▓",
                "▓▓QQQQQQQ▓▓",
                "▓QQQ▓▓▓QQQ▓",
                "▓QQQ▓▓▓QQQ▓",
                "▓QQQ▓▓▓QQQ▓",
                "▓QQQ▓Q▓QQQ▓",
                "▓QQQ▓▓QQQ▓▓",
                "▓▓QQQQQQ▓Q▓",
                "▓▓▓▓▓▓▓▓▓▓▓"
            ]
        },
        {
            "symbol":"R",
            "draw":[
                "▓▓▓▓▓▓▓▓▓▓▓",
                "▓RRRRRRR▓▓▓",
                "▓RR▓▓▓▓RR▓▓",
                "▓RR▓▓▓RR▓▓▓",
                "▓RRRRRR▓▓▓▓",
                "▓RR▓▓▓RR▓▓▓",
                "▓RR▓▓▓▓RR▓▓",
                "▓RR▓▓▓▓▓RR▓",
                "▓▓▓▓▓▓▓▓▓▓▓"
            ]
        },
        {
            "symbol":"S",
            "draw":[
                "▓▓▓▓▓▓▓▓▓▓▓",
                "▓▓▓SSSS▓▓▓▓",
                "▓▓SS▓▓SS▓▓▓",
                "▓▓▓S▓▓▓▓▓▓▓",
                "▓▓▓▓SS▓▓▓▓▓",
                "▓▓▓▓▓SS▓▓▓▓",
                "▓▓S▓▓SSS▓▓▓",
                "▓▓▓SSSS▓▓▓▓",
                "▓▓▓▓▓▓▓▓▓▓▓"
            ]
        },
        {
            "symbol":"T",
            "draw":[
                "▓▓▓▓▓▓▓▓▓▓▓",
                "▓TTTTTTTTT▓",
                "▓TTTTTTTTT▓",
                "▓▓▓▓TTT▓▓▓▓",
                "▓▓▓▓TTT▓▓▓▓",
                "▓▓▓▓TTT▓▓▓▓",
                "▓▓▓▓TTT▓▓▓▓",
                "▓▓▓▓TTT▓▓▓▓",
                "▓▓▓▓▓▓▓▓▓▓▓"
            ]
        },
        {
            "symbol":"U",
            "draw":[
                "▓▓▓▓▓▓▓▓▓▓▓",
                "▓UUU▓▓▓UUU▓",
                "▓UUU▓▓▓UUU▓",
                "▓UUU▓▓▓UUU▓",
                "▓UUU▓▓▓UUU▓",
                "▓UUU▓▓▓UUU▓",
                "▓UUU▓▓▓UUU▓",
                "▓▓UUUUUUU▓▓",
                "▓▓▓▓▓▓▓▓▓▓▓"
            ]
        },
        {
            "symbol":"V",
            "draw":[
                "▓▓▓▓▓▓▓▓▓▓▓",
                "▓VV▓▓▓▓▓VV▓",
                "▓VVV▓▓▓VVV▓",
                "▓VVV▓▓▓VVV▓",
                "▓VVV▓▓▓VVV▓",
                "▓VVVV▓VVVV▓",
                "▓VVVVVVVVV▓",
                "▓▓▓▓VVV▓▓▓▓",
                "▓▓▓▓▓▓▓▓▓▓▓"
            ]
        },
        {
            "symbol":"W",
            "draw":[
                "▓▓▓▓▓▓▓▓▓▓▓",
                "▓WW▓▓▓▓▓WW▓",
                "▓WW▓▓W▓▓WW▓",
                "▓WW▓▓W▓▓WW▓",
                "▓WW▓▓W▓▓WW▓",
                "▓WW▓▓W▓▓WW▓",
                "▓WW▓▓W▓▓WW▓",
                "▓▓WWWWWWW▓▓",
                "▓▓▓▓▓▓▓▓▓▓▓"
            ]
        },
        {
            "symbol":"X",
            "draw":[
                "▓▓▓▓▓▓▓▓▓▓▓",
                "▓XX▓▓▓▓▓XX▓",
                "▓▓XX▓▓▓XX▓▓",
                "▓▓▓▓XXX▓▓▓▓",
                "▓▓▓▓▓X▓▓▓▓▓",
                "▓▓▓▓XXX▓▓▓▓",
                "▓▓▓XX▓▓XX▓▓",
                "▓▓XX▓▓▓▓XX▓",
                "▓▓▓▓▓▓▓▓▓▓▓"
            ]
        },
        {
            "symbol":"Y",
            "draw":[
                "▓▓▓▓▓▓▓▓▓▓▓",
                "▓YY▓▓▓▓▓YY▓",
                "▓▓YY▓▓▓YY▓▓",
                "▓▓▓▓Y▓Y▓▓▓▓",
                "▓▓▓▓YYY▓▓▓▓",
                "▓▓▓▓YYY▓▓▓▓",
                "▓▓▓▓YYY▓▓▓▓",
                "▓▓▓▓YYY▓▓▓▓",
                "▓▓▓▓▓▓▓▓▓▓▓"
            ]
        },
        {
            "symbol":"Z",
            "draw":[
                "▓▓▓▓▓▓▓▓▓▓▓",
                "▓ZZZZZZZZZ▓",
                "▓▓▓▓▓▓▓▓Z▓▓",
                "▓▓▓▓▓▓▓Z▓▓▓",
                "▓▓▓▓▓▓Z▓▓▓▓",
                "▓▓▓▓▓Z▓▓▓▓▓",
                "▓▓▓ZZ▓▓▓▓▓▓",
                "▓ZZZZZZZZZ▓",
                "▓▓▓▓▓▓▓▓▓▓▓"
            ]
        }
        ,
        {
            "symbol":" ",
            "draw":[
                "▓▓▓▓▓▓▓▓▓▓▓",
                "▓▓▓▓▓▓▓▓▓▓▓",
                "▓▓▓▓▓▓▓▓▓▓▓",
                "▓▓▓▓▓▓▓▓▓▓▓",
                "▓▓▓▓▓▓▓▓▓▓▓",
                "▓▓▓▓▓▓▓▓▓▓▓",
                "▓▓▓▓▓▓▓▓▓▓▓",
                "▓▓▓▓▓▓▓▓▓▓▓",
                "▓▓▓▓▓▓▓▓▓▓▓"
            ]
        }
    ]
}
function writer(){
    autoClean();
    var dataText= document.getElementById("textTransform").value.toUpperCase();
    var cleanedText= dataText.replace(/[^a-zA-Z ]/g, '');
    for(var i=0;i<cleanedText.length;i++){
       renderWord(cleanedText[i])
    }  
}
function autoClean(){
    var element= document.getElementById("myList");
    while (element.firstChild) {
        element.removeChild(element.firstChild);
      }
}
function cleanTextbx(){
    document.getElementById("textTransform").value="";
}
function renderWord(keyword){
function findLetter(word){
    return word.symbol === keyword;
}
var finder=letters.letters.find(findLetter)
for(var n=0;n<finder.draw.length;n++){
    var node = document.createElement("LI");
    var textnode = document.createTextNode(`${finder.draw[n]}`);
    node.appendChild(textnode);
    document.getElementById("myList").appendChild(node);
}
}
